apiVersion: v1
kind: Secret
metadata:
    name: ghcr-credential-secrets
    namespace: argocd
stringData:
    creds: ENC[AES256_GCM,data:sgGLvVGLjIPZwMcJydzaDgMEgMTyY6HZlzMctf8yS+IODdpSgj7d9R+wBKrdbySluuzX,iv:5EOEyzbzqBM2IU/HpEH72QhM/3l+dyZzH2AZRKNPdPU=,tag:2Ad4dxpcnMsVCZE+EA1rzg==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1qadccpnp7yhrs8vg52cjvkh40a7gfrvwvdzqjnhzpvvtnqqpzy0qh47fm9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0ZGVDeDJmL1pqMzJWSkdE
            TDZSZVh3MmZlaHJqNFFTaS9SV2hwaHovY0ZBCm1hWnVCazUyT3BqaXNwdGU0WFZQ
            SVBzbHdad08vdnVzOEJ2eDNNOE1lNUkKLS0tIElDRTBTaHl2K3lETy95bzdJTnpH
            NDcwakJwREk2T2RuNVY5Y2RLWHpULzAKpPt51IB0tXgRL+yKgEZM4z6XbybexwWi
            lf2jqG034wa8sgS58LjSWskqcTajqrsgHsh+12s2TnMCqhYHO47OMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T03:40:17Z"
    mac: ENC[AES256_GCM,data:TyOauItI6jUwT2mi8Q9//p/wn1ORsacGw76EV/hgBDLEGVMssBubMCpM9GuDq3SgXXa8jfHPnbjv5GnXTenUuZh/XaHMpRQtSTQKcFxhd9D793HhiQ4Ahj93R42tgc9Jfgzu9TOZOjphIbh0fl0I4r5L5SnXJ1Xe6y8o8bofeFo=,iv:OIUkirAJBI21OA8MMOcWn51MF2xmfheS+qPWS9CqjbM=,tag:DeaSHFlp+jj7muuoHqJxqg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
